services:
  evoucher:
    container_name: evoucher
    image: golang_1_22
    hostname: evoucher
    ports:
      - 8678:8678
    networks:
      - devnetwork 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./..:/var/www/html:consistent

    command: /var/www/html/runlocal.go
    working_dir: /var/www/html
    


networks:
  devnetwork:
    name: devnetwork
    external: true




